--  Warning this file will permentally erase all of the tables in the family-choreboard.
--  DROP FUNCTION insert_transaction() CASCADE;
--  DROP FUNCTION update_chore_to_user() CASCADE;
--  DROP TABLE transactions;
--  DROP TABLE chores_to_users;
--  DROP TABLE task_to_chore;
--  DROP TABLE tasks;
--  DROP TABLE chores;
--  DROP TABLE users;
--  DROP TYPE transactionType;
--  CREATE TYPE transactionType AS ENUM ('dough', 'bonus', 'purchase', 'jurnaled');
